id = "ae2-neoforge"
version = "19.2.17"

[package]
name = "Applied Energistics 2 (NeoForge Edition)"
authors = ["Team AppliedEnergistics"]
description = "A Mod about Matter, Energy and using them to conquer the world..."
license = "LGPL-3.0-only"

[dependencies]
vanilla = "=1.21.1"
neoforge = ">=21.1.169"
guideme = ">=21.1.1"

[[install.mc-mod]]
blake3 = "e2f8dacfb626a6fa6ef796242dd77117adc98a6698be64c8dc2e6476d9e04fe7"
name = "appliedenergistics2-19.2.17.jar"
src = "https://cdn.modrinth.com/data/XxWD5pD3/versions/kfyIqgJ6/appliedenergistics2-19.2.17.jar"
len = 8230896
