id = "sodium"
version = "0.6.13+mc1.21.1"

[dependencies]
vanilla = "=1.21.1"

[[either-dependency]]
sodium-neoforge = "=0.6.13+mc1.21.1"
sodium-fabric = "=0.6.13+mc1.21.1"

[package]
name = "Sodium"
authors = ["JellySquid (jellysquid3)", "IMS212"]
description = """
Sodium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
"""
license = "LicenseRef-Polyform-Shield-1.0.0"
